### ISSUE TITLE
lots of new issues to discuss with the team

### ISSUE THREAD

**Issue by walterjamesperry** [allenharborth9835/Community-Connect#13]
Here is a long list of issues.
Each one should be discussed separately or just fixed.
- Consider changing the name of your DB? to your new team name. No problem if you do not do this.
- Add node_modules to you .gitignore file
- Your team is using a package called “connect-session-sequelize” in your server.js file. This package is not installed by package.json. remove that line of code or npm install the package.
------------------------------------------
You might want to use this in your server.js
server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
----------------------------------------------------------
Make Sur to put this in your package.json file inside the scripts
"start": "node server.js",
That way everyone can nom run start
----------------------------------------------------------
I am unable to run your main branch server because of an error in package.json
You installed a package called express-sessions that is the wrong package
When I try to start the server it is looking for a package called express-session. No s on the end of the package name
----------------------------------------------------------------

These are just some things to correct in your starting code.

**Comment by allenharborth9835** [comment]
added express-sessions and connect-session-sequelize to make server.js run, added start script, and updated DB in my branch.
